### ISSUE TITLE
Autoload failed 

### ISSUE THREAD

**Issue by kirillkomlev** [codacy/php-codacy-coverage#11]
Hello. 

This is mistake in https://github.com/codacy/php-codacy-coverage/blob/master/bin/codacycoverage#L5

Why this line should be looked for first? 

It's really *BAD* idea use `vendor/bin` at first.

For example, I have global installed codacycoverage. I go to  a project with vendor dir, where codacycoverage not installed (but has autoload.php). So codacycovarage take those autoload instead own.

I test various situation with codacycoverage:
- global installed
- project installed (from composer)
- codacycoverage installed from `git clone`

and run codacycoverage with different platform (Windows, Linux, Mac OS X) in differrent folders (in root repo, in vendor dir, in /tmp dir, in repo dir with vendor without codacycoverage installed). It's work fine with those lines:

```php
$files = array(
    __DIR__ . "/../../vendor/autoload.php",
    __DIR__ . "/../../../autoload.php",
    dirname(__DIR__) . "/vendor/autoload.php"
);
```
*NO other line* should specified.

A line ```"vendor/autoload.php``` really buggy, and not work. *Please, remove it*.

**Comment by kirillkomlev** [comment]
Line `dirname(__DIR__) . "/vendor/autoload.php"` means `../vendor/autoload.php`, but in this situation a base dir -- where codacycoverage located (in git repo it's `bin` folder). 

You may specify this line first, it is the same meaning like `vendor/autoload.php` but work correct.

**Comment by haffla** [comment]
Sorry my bad. Again, I had not thought of people who want to call codacycoverage from a totally different folder than the project root. BUT, I had found a situation where only ```"vendor/autoload.php"``` work: when building a .phar. But you are right, this one should be looked for last.
