### ISSUE TITLE
Getting 404 on codacy API

### ISSUE THREAD

**Issue by captn3m0** [codacy/php-codacy-coverage#13]
[The project API token is exported](https://travis-ci.org/razorpay/ec2-metadata/jobs/68203159#L82), but the codacy upload fails: https://travis-ci.org/razorpay/ec2-metadata/jobs/68203159#L194
                                                                             
```[Exception]
Error: call to URL https://www.codacy.com/api/2.0/coverage/2b4fbcdbf29fd6359165fb6eadd5ae319457609e/php failed with status 404, response {"error":"not found"}, curl_error 0
```

I tried running it locally and got the same error.

**Comment by mrfyda** [comment]
This is was related with our architecture rather than this reporter.
The is now fixed.

@captn3m0 please use in-app support if you require further assistance.

Cheers
