### ISSUE TITLE
Uncaught error - curl_init() undefined

### ISSUE THREAD

**Issue by msencenb** [codacy/php-codacy-coverage#22]
Hey guys,

I'm trying to upload code coverage via a new ubuntu 14.04 installation that I've setup with Jenkins (I've managed to get code coverage working on my local mac). After I run unit tests, I issue the following command:

`php vendor/bin/codacycoverage clover tests/coverage.xml`

and end up with this stack trace:
```
PHP Fatal error:  Uncaught Error: Call to undefined function Codacy\Coverage\Util\curl_init() in /var/lib/jenkins/workspace/develop-test/vendor/codacy/coverage/src/Codacy/Coverage/Util/CodacyApiClient.php:30
Stack trace:
#0 /var/lib/jenkins/workspace/develop-test/vendor/codacy/coverage/src/Codacy/Coverage/Command/Clover.php(69): Codacy\Coverage\Util\CodacyApiClient->sendCoverage('a5b73dac5497864...', '{"total":44,"fi...')
#1 /var/lib/jenkins/workspace/develop-test/vendor/symfony/console/Command/Command.php(259): Codacy\Coverage\Command\Clover->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/lib/jenkins/workspace/develop-test/vendor/symfony/console/Application.php(844): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/lib/jenkins/workspace/develop-test/vendor/symfony/console/Application.php(192): Symfony\Component\Console\Application->doRunCom in /var/lib/jenkins/workspace/develop-test/vendor/codacy/coverage/src/Codacy/Coverage/Util/CodacyApiClient.php on line 30
```

Any ideas?

**Comment by machadoit** [comment]
Hi @msencenb 

We depend on curl extension in our coverage plugin, to add it you can:
```
sudo apt-get install php5-curl
```

It's ok for you to install this decency? If not, please open another issue so we can consider our plugin without that dependency for a future release.

Please let me know if this solves your problem.

**Comment by msencenb** [comment]
@machadoit Thank you, and sorry for the dumb question. Curl was running fine on my box, but I forgot that I also needed to install the php extension too. My jenkins job is running perfectly now, thanks!
