### ISSUE TITLE
Dependency problem with grumphp

### ISSUE THREAD

**Issue by drupol** [codacy/php-codacy-coverage#27]
Hi,

The [grumphp](https://packagist.org/packages/phpro/grumphp) project needs gitlib ~1.0 while Codacy coverage needs ~0.1

Would it be possible to update Codacy and use version ~1.0 of Gitlib ?

**Comment by rtfpessoa** [comment]
Sure. Feel free to send a PR.

**Comment by ottlinger** [comment]
Tests are green after updating the gitlib dependency
see https://github.com/codacy/php-codacy-coverage/compare/master...ottlinger:master

**Comment by rtfpessoa** [comment]
Released as version `1.1.0`
