### ISSUE TITLE
Problems integrating php-codacy-coverage via travis / is file structure valid?

### ISSUE THREAD

**Issue by ottlinger** [codacy/php-codacy-coverage#29]
I've integrated codacy coverage into my existing PHP project.

The builds fail on Travis with:
```
3.99s$ travis_retry php composer.phar install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
                                                                                                                                                             
  [RuntimeException]                                                                                                                                         
  Could not scan for classes inside "/home/travis/build/ottlinger/hornherzogen/vendor/codacy/coverage/src/" which does not appear to be a file nor a folder  
```
upon build initialization.

Somehow the file structure does not seem to be valid for composer ....
https://travis-ci.org/ottlinger/hornherzogen/jobs/218432170

### PHP Version

* 7.0
* 7.1

### Test framework 

* PhpUnit 6.x
* Composer: Composer version 1.4.1 2017-03-10 09:29:45

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Use `uname -a` if on Linux.

### Library Dependencies

If this is an issue that involves integration with another system, include the exact version and OS of the other system, including any intermediate drivers or APIs i.e. if you connect to a PostgreSQL database, include both the version / OS of PostgreSQL and the JDBC driver version used to connect to the database.

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

* The builds should go through as they do locally.

**Comment by ottlinger** [comment]
The problematic version is in the branch:
https://github.com/ottlinger/hornherzogen/tree/php-codacy-coverage/issues/29

I'll try to revert master to see if the issue is directly connect to introducing php-codacy-coverage.

**Comment by ottlinger** [comment]
The problem seems to be related to the Travis integration - can you test-integrate the project itself into Travis to verify if the same failure happens?

After I've removed the integration, builds are green again:
https://travis-ci.org/ottlinger/hornherzogen/jobs/218445334

**Comment by haffla** [comment]
The lib is made to work with CI like Travis, the problem lies somewhere else.

**Comment by ottlinger** [comment]
@haffla can you activate the travis integration? I'd love to see if it fails with the same error message ... a working PHP-project with integration of php-codacy-coverage  in Travis would be better, but maybe the failure happens as well ?!

**Comment by haffla** [comment]
Wouldn't it be better to setup some test project with some fake tests and integrate php-codacy-coverage there? But as I said, it is known to work with php-codacy-coverage. I just don't have an example at hand now.

**Comment by rtfpessoa** [comment]
I actually enabled the travis integration a couple of minutes ago, but you might need to amend or push a commit for it to start.

But as @haffla said we moved from travis in the past and it was working. Although I do not mind having it running for the sake of example for other users.

**Comment by haffla** [comment]
I forked a famous PHP project and added php-codacy-coverage: https://travis-ci.org/haffla/socialite/builds/218459127

**Comment by ottlinger** [comment]
@haffla your project does not work with a new PHPUnit (but 5.x) only. 
Composer seems to be the same version.

**Comment by haffla** [comment]
@ottlinger I forked your project and added php-codacy-coverage and it works. See https://travis-ci.org/haffla/hornherzogen. I believe your problem could be that your `vendor` folder is in version control. This is not good. You usually only need to track `composer.json` and `composer.lock`. The `vendor` is for the locally caching the dependencies.

**Comment by ottlinger** [comment]
@haffla thanks for the info - I though that checking in the vendor folder would speedup the builds.
I've adapted my branches to not contain the vendor folder.

I'll wait another day to see if any coverage results show up in codacy before submitting a PR that changes the travis example in the documentation. 

Thanks for your help and insights!

**Comment by ottlinger** [comment]
@haffla @rtfpessoa the builds are not failing anymore, but the coverage integration into codacy is not working. I close this issue as the way an integration might work is clear now.

Thanks again for your help and assistance.
