### ISSUE TITLE
Use phar in git repo is ugly

### ISSUE THREAD

**Issue by kirillkomlev** [codacy/php-codacy-coverage#4]
Hello, everybody. 

Why are you store `bin/phar/codacycoverage.phar` in git repo? If I want modify some of files, I need regenerate this phar file. It's not hard, but really duplicate your code and seem ugly. 

I don't know projects, that use phar like you. Many projects has phar.builder script, that can generate phar in they repo, but doesn't store phar. 

Why I need download 21Kb (your phar size) unusefull traffic, when install dependency from composer?

I have looked your documentation for word `phar` (in this project and in http://docs.codacy.com) and have n't find any requirements or code example that use this phar. 

Could you remove it from your repo?

**Comment by haffla** [comment]
Remove in https://github.com/codacy/php-codacy-coverage/commit/ceefe5649b4940b35651095fcb1506b55d39de39.
