### ISSUE TITLE
 Hey Seems like we stopped receiving your coverage results. Check your CI server!

### ISSUE THREAD

**Issue by emamerto** [codacy/php-codacy-coverage#40]
### Issue 
Coverage received successfully, but not displaying in Codacy

### PHP Version
Tried it on 7 and 5.6

### Operating System 
Tried it on Mac and Linux

### Expected Outcome
Coverage should display in the Codacy Dashboard and File page

### Steps to reproduce the issue
**Step 1** - Installed codacy/coverage (I preferred globally)
```
$ composer require global codacy/coverage
```
**Step 2** - export token on terminal
```
$ export CODACY_PROJECT_TOKEN=<project_api_token>
```
![image](https://user-images.githubusercontent.com/42442596/44213183-1e66dc00-a13b-11e8-95fc-3da50531a9d2.png)
**Step 3** - Send clover xml file to Codacy
```
$ ~/.composer/vendor/bin/codacycoverage clover path/to/clover.xml -v
```
### Actual Outcome

**Terminal Output**

![image](https://user-images.githubusercontent.com/42442596/44213554-f88e0700-a13b-11e8-959c-27e639d99cac.png)

**Codacy Error's Message**

![image](https://user-images.githubusercontent.com/42442596/44213485-ced4e000-a13b-11e8-89a9-22002d022f87.png)

**Comment by rtfpessoa** [comment]
@emamerto can you open a ticket with `support at codacy dot com` so they can track the specific case of your project?

From here the only thing I would suggest would be to check which commits you are sending coverage to.
I would recommend sending coverage from a build server like CircleCI or TravisCI automatically for every commit.

**Comment by emamerto** [comment]
@rtfpessoa Additionally I am using Bitbucket Server and we use Bamboo for our build system, but I doubt that sending it from bamboo would make a difference since machine I was sending it from is identical. 

Maybe specifying the commit would solve the issue, I would try this before sending a ticket to support. Thank you!

**Comment by rtfpessoa** [comment]
The build server is just to make sure you are sending for every commit.

About support is so they can check the project internally and see if there is any problem they can detect.

**Comment by emamerto** [comment]
@rtfpessoa Thanks! My intention is to test my config so I was sending it manually. 

So I just tried adding the commit hash of the last commit, and it's the same result 👎. 

I'll check with support. Thank you!

**Comment by rtfpessoa** [comment]
Closing this issue here since there is not much we can do here. Let me know if we need to re-open.

**Comment by angelxmoreno** [comment]
I am having the same issue. Recently stopped working

**Comment by rtfpessoa** [comment]
@angelxmoreno please follow the same steps for support to be able to help you.

**Comment by smohanty-mdsol** [comment]
I am having the same issue. Recently stopped working. Codacy report is sending to codacy correctly. But the project status in showing Inactive in codacy.

**Comment by fasatrix** [comment]
Same here

**Comment by fasatrix** [comment]
> I am having the same issue. Recently stopped working

@angelxmoreno @smohanty-mdsol have you guys got it resolved upon contacting the support?

**Comment by angelxmoreno** [comment]
@fasatrix Sorry, I do not recall

**Comment by smohanty-mdsol** [comment]
Hi Fabio,

I am not facing this issue right now. Thanks


Thanks & Regards
Santosh M

**Comment by sgongar** [comment]
Same error here. Suddenly stop working, everything is alright at CircleCi side.
