### ISSUE TITLE
folder vs. path (phpunit vs clover)

### ISSUE THREAD

**Issue by davidsneighbour** [codacy/php-codacy-coverage#41]
### PHP Version

PHP 7.2.10-0ubuntu1 (cli) (built: Sep 13 2018 13:38:55) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.10-0ubuntu1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.7.0beta2-dev, Copyright (c) 2002-2018, by Derick Rethans

### Test framework 

Codeception 2.5.3

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Linux bookra 4.18.0-15-generic #16-Ubuntu SMP Thu Feb 7 10:56:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Actual Behavior

Running

```
./bin/codacycoverage clover ./tmp/coverage.xml
```
works (coverage.xml exists). Running

```
./bin/codacycoverage phpunit ./tmp/coverage.xml
```

throws error

```
In Parser.php line 50:                                                                               
  Unable to load the xml file. Make sure path is properly set. Using: "/home/  
  patrick/Projects/Booka/tmp/coverage.xml/index.xml"            
```

### Expected

I would expect to have at least the same behaviour, EITHER filename OR directory. Otherwise the documentation (README.md) should state the difference.

**Comment by IGFCoimbra** [comment]
Hi @davidsneighbour 

I'm very sorry for the time it took to get back to you.

If you are still having this error, can you please reach out to support@codacy.com so we can help you with this?

Regards,
Ivo

**Comment by mrfyda** [comment]
@davidsneighbour we're deprecating this reporter in favor of https://github.com/codacy/codacy-coverage-reporter.
the new reporter is language agnostic, easier to install and contains many bug fixes that were never ported to this reporter.
