### ISSUE TITLE
In ReferenceBag: Unable to parse "refs/original/refs/heads/master"

### ISSUE THREAD

**Issue by StanBarrows** [codacy/php-codacy-coverage#43]
### PHP Version
7.3

### Test framework 
Laravel / PHPUnit

### Operating System
* MacOS | 10.14.6
* Homestead | v9.0.0
* Settler | v8.0.0
* Virtual Box |  6.0.12
* Ubuntu |  18.04.3 LTS (GNU/Linux 4.15.0-58-generic x86_64)

### Actual Behavior
**Commands**
```
php vendor/bin/phpunit --coverage-clover build/coverage/xml

php vendor/bin/codacycoverage clover build/coverage/xml
```

<img width="738" alt="image" src="https://user-images.githubusercontent.com/10268813/67119030-8bb24900-f1e6-11e9-9c6a-5c3e006327e1.png">

### Code
**composer.json**
```
   "require-dev": {
        "codacy/coverage": "^1.4",
    },

```

**phpunit.xml**
```
   <logging>
        <log type="coverage-html" target="./reports" lowUpperBound="50" highLowerBound="80" />
    </logging>
```

**Comment by Laracodacy** [comment]
We will address this by migrate the PHP format to codacy-coverage reporter (which is in progress).

**Comment by mrfyda** [comment]
@StanBarrows we're deprecating this reporter in favor of https://github.com/codacy/codacy-coverage-reporter. a new version is available now!
the new reporter is language agnostic, easier to install and contains many bug fixes that were never ported to this reporter.
