### ISSUE TITLE
Return 404  codacy API

### ISSUE THREAD

**Issue by wallaceSF** [codacy/php-codacy-coverage#46]
Hello, everyone I am trying to do the integration, but ends up returning this error.

In CodacyApiClient.php line 54:

**Error: Call to URL https://api.codacy.com/2.0/coverage/3c7760d2a5adc8a9c4453d8a208a35a630c13f93/php failed with status 404, response {"error": "not found"}, curl_error 0**

**Comment by josemiguelmelo** [comment]
Hello,

Can you confirm `CODACY_PROJECT_TOKEN` env variable is set correctly? Check here: https://github.com/codacy/php-codacy-coverage#updating-codacy

**Comment by wallaceSF** [comment]
Sorry friend for taking so long to answer. The problem was the token.
Thank you for your attention.
