### ISSUE TITLE
Use symfony/console for bin/codacycoverage

### ISSUE THREAD

**Issue by kirillkomlev** [codacy/php-codacy-coverage#9]
I can help you to rewrite ugly bin/codacycoverage by using symfony/console dependcies (this add requirements in composer.json)

This will be like this: 
```php
#!/usr/bin/env php
<?php

require 'vendor/autoload.php';

$app = new \Codacy\Coverage\Application();
$app->run();
```

And split `clover` and `phpunit` by dedicated \Codacy\Coverage\Command classes. 

I can do this work, if you wanted.

**Comment by haffla** [comment]
Sounds good. Would be nice if codacycoverage could be started interactively then. But the current behaviour (``` codacycoverage clover ``` or ``` codacycoverage clover build/cover/clover.xml ```) should still be possible. If you want to do this, go ahead. Can you make it a pull request and incorporate all your other pull requests?

**Comment by kirillkomlev** [comment]
Good. I'll do it tomorrow.
